id: AB99BBBEB
title: Sang Offering to Yellow Jambhala
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:00:17.271927
  last_modified_at: 2022-03-01 04:00:17.271931
