id: AB99BBBEB
title: 'The Falling Rain of Blessings: A Brief Daily Practice of the Wealth Deity
  White Jambhala'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:00:17.273106
  last_modified_at: 2022-03-01 04:00:17.273109
